apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-webserver
  name: simple-webserver
  namespace: simple-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webserver
  template:
    metadata:
      labels:
        app: simple-webserver
    spec:
      containers:
      - image: msassignment.azurecr.io/simple-webserver:1.0
        imagePullPolicy: Always
        name: simple-webserver
