name: CI/CD pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  workflow:
    uses: AkyshBaymuhammedov/workflow-templates/.github/workflows/cicd-workflow.yml@main
    with:
      REPO_NAME: ${{ github.event.repository.name }}
      NAMESPACE: ${{ github.event.repository.name }}
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      KEY_VAULT: ${{ secrets.KEY_VAULT }}
